### ISSUE TITLE
Hope to get a more detailed installation description

### ISSUE THREAD

**Issue by emineh** [Microsoft/DLWorkspace#143]
1.When I tried to setup the development environment, I found the [installation description](https://github.com/Microsoft/DLWorkspace/blob/alpha.v1.5/docs/DevEnvironment/Readme.md) says there exists a  'src/ClusterBootstrap/deploy'  folder which contains important information to access the deployed DL workspace cluster, but I could not find such a folder.
2.After I ran the following command, I could not get to the '/home/DLWorkspace/src/ClusterBootstrap' folder.

```
git clone https://github.com/microsoft/DLWorkspace
docker run -ti -v DLWorkspace:/home/DLWorkspace jinl/dlworkspacedevdocker /bin/bash
cd /home/DLWorkspace/src/ClusterBootstrap
```

These are operated on the Ubuntu 16.04 system.

**Comment by emineh** [comment]
As for the second problem, I try to modify the path of the first ‘DLWorkspace’ to the absolute path and this problem is solved.

**Comment by resouer** [comment]
`src/ClusterBootstrap/deploy` should appear after you finished installation :)

**Comment by emineh** [comment]
@resouer Thank you for your reply. But I meet some other questions in the following installation process:
When [setting up the cluster](https://github.com/Microsoft/DLWorkspace/blob/alpha.v1.5/docs/deployment/configuration/Readme.md),  I found the instruction is too brief. There is no config.yaml in the '/src/ClusterBootstrap' folder, just three similar  files with names ending in the.yaml.template sufiix.  I copied the config_philly.yaml.template file and rename it 'config.yaml'. After I set the important information of the cluster(e.g., cluster name, number of Etcd servers used), I use this command `./deploy.py backup [backup_file_prefix] [password]` to backup cluster configuration, while an error occurring:

> Traceback (most recent call last):
  File "./deploy.py", line 3660, in <module>
    run_command( args, command, nargs, parser)
  File "./deploy.py", line 2933, in run_command
    merge_config(config, yaml.load(f))
  File "/usr/local/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 39, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 48, in construct_document
    for dummy in generator:
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 208, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 132, in construct_mapping
    "found unacceptable key (%s)" % exc, key_node.start_mark)
yaml.constructor.ConstructorError: while constructing a mapping
  in "/home/DLWorkspace/src/ClusterBootstrap/config.yaml", line 4, column 22
found unacceptable key (unhashable type: 'dict')
  in "/home/DLWorkspace/src/ClusterBootstrap/config.yaml", line 4, column 23

Then I commented out the following lines in the config.yaml and ran the command `./deploy.py backup [backup_file_prefix] [password]` again, however,  another error occurred.
`sqlserver-hostname : {{}}
sqlserver-username : {{}}
sqlserver-password : {{}}
sqlserver-database : {{}}`

error:

> cp: cannot stat './deploy/clusterID.yml': No such file or directory
./deploy_backup/backup/
./deploy_backup/backup/config.yaml
./deploy_backup/backup/clusterID/
./deploy_backup/backup/ssl/
./deploy_backup/backup/sshkey/

I have never deployed similar cluster before, so I am really confused about the installation guidance. I have saw the subsequent guidance which is still very sketchy.  I was wondering if there is a more detailed guidance for the newbie like me. 
Thank you for your time.

**Comment by resouer** [comment]
It's expect for you to copy one of config_* as a template. I would suggest use azure template which should be easiest.

**Comment by emineh** [comment]
@resouer I met so many problems during the deployment and felt hard to finish it on the Ubuntu 16.04 system. I wonder have you ever deployed this project using the azure template successfully and whether the installation description for the azure template is really helpful for the user :)

**Comment by resouer** [comment]
@emineh That's funny, what makes you think https://github.com/Microsoft/DLWorkspace/blob/alpha.v1.5/docs/deployment/configuration/Readme.md is the deployment guide?

As I [mentioned here](https://github.com/Microsoft/DLWorkspace/issues/143#issuecomment-362054065), I would suggested you to play with Azure deploy, which obviously, refers to [this guide](https://github.com/Microsoft/DLWorkspace/blob/alpha.v1.5/docs/deployment/Azure/Readme.md), it is written with **bold lines** in [README](https://github.com/Microsoft/DLWorkspace/blob/alpha.v1.5/docs/deployment/Readme.md#azure-cluster) ...

Here's exactly the config.yaml I am using, which is "sketchy" because it is designed to be "sketchy":

```yaml
cluster_name: harrydevbox

azure_cluster:
  harrydevbox:
    infra_node_num: 1
    infra_vm_size : Standard_D3_v2
    worker_node_num: 2
    worker_vm_size: Standard_D3_v2
    azure_location: westus

UserGroups:
  DLWSAdmins:
    Allowed: [ "xxxx@gmail.com" ]
    uid : "20000"
    gid : "20001"
  DLWSRegister:
    Allowed: [ "@gmail.com" ]
    uid : "20001-29999"
    gid : "20001"

WebUIregisterGroups: [ "DLWSRegister"]
WebUIauthorizedGroups: [ "DLWSAdmins" ]
WebUIadminGroups: ["DLWSAdmins"]

DeployAuthentications : ["Corp", "Gmail", "Live"]

WinbindServers: []

webuiport: 3080
```

Please stop complaining and read the **right** docs.
